version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/the-botch"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
    groups:
      prisma-all:
        patterns:
          - "prisma"
          - "@prisma/client"
          - "@prisma/adapter-pg"
      radix-ui:
        patterns:
          - "@radix-ui/*"
    ignore:
      - dependency-name: typescript
        update-types: [version-update:semver-major]
      - dependency-name: prisma
        update-types: [version-update:semver-major]
      - dependency-name: "@prisma/client"
        update-types: [version-update:semver-major]
      - dependency-name: "@types/node"
        update-types: [version-update:semver-major]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
